title: "Mountain Cat's D&D"
description: "Mountain Cat's house rules"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark
  
markdown: kramdown

header_pages:
  - index.md

