title: "Mountain Cat's D&D"
description: "Mountain Cat's house rules"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

markdown: kramdown

minima:
  skin: dark

header_pages:
  - index.md

