remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

title: "DnD House Rules"
description: "Mountain Cat's house rules"

minima:
  skin: dark  # or "auto" to follow system theme

collections:
  pages:
    output: true
    permalink: /:name/
