remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

title: "Mountain Cat's D&D"
description: "Mountain Cat's house rules"

minima:
  skin: dark  # or "auto" to follow system theme

header_pages:
  - index.md
